Repository codeforamerica/la-doc-uploader, pull requests merged in 2024-01, with the labels that each got.

#476 Updating submission transfer to use Transmission db
  src/main/java/org/ladocuploader/app/cli/SubmissionTransfer.java
  src/main/java/org/ladocuploader/app/data/TransmissionRepository.java
  src/main/java/org/ladocuploader/app/data/enums/TransmissionType.java
  src/main/java/org/ladocuploader/app/submission/actions/HandleApplicationSigned.java
  src/main/resources/db/migration/V2023.12.21.16.15.18__add_batch_sequence.sql
  src/test/java/org/ladocuploader/app/cli/SubmissionTransferTest.java
  src/test/resources/inputs/applicant1_birth-certificate.jpeg
  src/test/resources/inputs/applicant1_license.jpeg
  src/test/resources/inputs/applicant1_pay-stub.png
Labels: ready for review

#493 Retrieving pgp keys from s3
  .github/workflows/deploy-staging.yaml
  src/main/java/org/ladocuploader/app/cli/FtpsClientImpl.java
  src/main/java/org/ladocuploader/app/cli/MockFtpsClientImpl.java
  src/main/java/org/ladocuploader/app/cli/MockPGPEncryptorImpl.java
  src/main/java/org/ladocuploader/app/cli/PGPEncryptor.java
  src/main/java/org/ladocuploader/app/cli/PGPEncryptorImpl.java
  src/main/java/org/ladocuploader/app/cli/SubmissionTransfer.java
  src/main/resources/application.yaml
  src/test/java/org/ladocuploader/app/cli/SubmissionTransferTest.java
Labels: ready for review

#495 using the FFL number template resolves the hours per week issue and d…
  src/main/resources/templates/fragments/inputs/number.html
Labels: ready for review

#484 finalized household pages and updated fragment syntax
  src/main/java/org/ladocuploader/app/data/enums/HomeExpensesType.java
  src/main/java/org/ladocuploader/app/data/enums/MedicalExpensesType.java
  src/main/java/org/ladocuploader/app/data/enums/UtilitiesExpenseType.java
  src/main/java/org/ladocuploader/app/inputs/LaDigitalAssister.java
  src/main/java/org/ladocuploader/app/preparers/HouseholdExpensesPreparer.java
  src/main/java/org/ladocuploader/app/preparers/MedicalExpensesPreparer.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/pdf-map.yaml
  src/main/resources/templates/fragments/inputs/phone.html
  src/main/resources/templates/laDigitalAssister/energyAssistance.html
  src/main/resources/templates/laDigitalAssister/expensesChildSupport.html
  src/main/resources/templates/laDigitalAssister/expensesChildSupportAmount.html
  src/main/resources/templates/laDigitalAssister/expensesDependentCare.html
  src/main/resources/templates/laDigitalAssister/expensesDependentCareAmount.html
  src/main/resources/templates/laDigitalAssister/expensesElderlyCare.html
  src/main/resources/templates/laDigitalAssister/expensesElderlyCareAmount.html
  src/main/resources/templates/laDigitalAssister/expensesSignPost.html
  src/main/resources/templates/laDigitalAssister/householdHomeExpenses.html
  src/main/resources/templates/laDigitalAssister/householdHomeExpensesAmount.html
  src/main/resources/templates/laDigitalAssister/householdMedicalExpenses.html
  src/main/resources/templates/laDigitalAssister/householdMedicalExpensesAmount.html
  src/main/resources/templates/laDigitalAssister/householdUtilities.html
  src/main/resources/templates/laDigitalAssister/householdUtilitiesAmount.html
  src/main/resources/templates/laDigitalAssister/liheap.html
  src/test/java/org/ladocuploader/app/journeys/LaDigitalAssisterFlowJourneyTest.java
  src/test/java/org/ladocuploader/app/preparers/HouseholdExpensesPreparerTest.java
  src/test/java/org/ladocuploader/app/preparers/MedicalExpensesPreparerTest.java
Labels: ready for review

#492 Adds PDF preparer code for race and ethnicity
  src/main/java/org/ladocuploader/app/data/enums/EthnicityType.java
  src/main/java/org/ladocuploader/app/data/enums/RaceType.java
  src/main/java/org/ladocuploader/app/preparers/ApplicantDetailsPreparer.java
  src/main/java/org/ladocuploader/app/preparers/HouseholdDetailsPreparer.java
  src/main/java/org/ladocuploader/app/utils/HouseholdUtilities.java
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/messages_vi.properties
  src/main/resources/pdf-map.yaml
  src/main/resources/pdfs/la_application_for_assistance.pdf
  src/main/resources/templates/laDigitalAssister/ethnicitySelection.html
  src/main/resources/templates/laDigitalAssister/raceSelection.html
  src/test/java/org/ladocuploader/app/data/SubmissionTestBuilder.java
  src/test/java/org/ladocuploader/app/journeys/AccessibilityJourneyPageTest.java
  src/test/java/org/ladocuploader/app/journeys/LaDigitalAssisterFlowJourneyTest.java
  src/test/java/org/ladocuploader/app/journeys/StaticPagesJourneyTest.java
  src/test/java/org/ladocuploader/app/preparers/HouseholdDetailsPreparerTest.java
  src/test/java/org/ladocuploader/app/preparers/PersonalSituationsPreparerTest.java
  src/test/java/org/ladocuploader/app/preparers/PregnancyDueDatePreparerTest.java
  src/test/java/org/ladocuploader/app/preparers/SpecialSituationsPreparerTest.java
  src/test/java/org/ladocuploader/app/preparers/SsnPreparerTest.java
  src/test/java/org/ladocuploader/app/submission/actions/SetExperimentGroupsTest.java
  src/test/java/org/ladocuploader/app/utils/AbstractBasePageTest.java
  src/test/java/org/ladocuploader/app/utils/AccessibilityTestPage.java
  src/test/java/org/ladocuploader/app/utils/Page.java
Labels: ready for review

#491 updated the household personal situations page
  src/main/java/org/ladocuploader/app/data/enums/PersonalSituationType.java
  src/main/java/org/ladocuploader/app/inputs/LaDigitalAssister.java
  src/main/resources/templates/laDigitalAssister/householdWhichPersonalSituations.html
Labels: InPM/DesignReview

#503 updated ssn type from text to ssn and changed validation rule
  src/main/java/org/ladocuploader/app/inputs/LaDigitalAssister.java
  src/main/resources/templates/laDigitalAssister/ssnForm.html
Labels: ready for review

#469 Document Type + Redirection
  src/main/java/org/ladocuploader/app/cli/SubmissionTransfer.java
  src/main/java/org/ladocuploader/app/config/DocUploadDisabledHandlerConfiguration.java
  src/main/java/org/ladocuploader/app/interceptors/DocUploadDisabledInterceptor.java
  src/main/java/org/ladocuploader/app/submission/actions/FinalizeDocuments.java
  src/main/java/org/ladocuploader/app/submission/conditions/IsDocUploadActive.java
  src/main/java/org/ladocuploader/app/utils/SubmissionUtilities.java
  src/main/resources/application.yaml
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/templates/laDigitalAssister/confirmation.html
  src/main/resources/templates/laDigitalAssister/docUploadRecommendations.html
  src/main/resources/templates/laDigitalAssister/signature.html
  src/test/java/org/ladocuploader/app/cli/SubmissionTransferTest.java
  src/test/java/org/ladocuploader/app/journeys/LaDigitalAssisterFlowJourneyTest.java
Labels: ready for review

#504 Remove choose programs screen
  src/main/java/org/ladocuploader/app/inputs/LaDigitalAssister.java
  src/main/java/org/ladocuploader/app/submission/conditions/ProgramsIncludeKscpOrFitap.java
  src/main/java/org/ladocuploader/app/submission/conditions/ProgramsIncludeSnap.java
  src/main/resources/flows-config.yaml
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/messages_vi.properties
  src/main/resources/templates/laDigitalAssister/choosePrograms.html
  src/test/java/org/ladocuploader/app/journeys/LaDigitalAssisterFlowJourneyTest.java
Labels: ready for review

#506 updated income flow
  src/main/java/org/ladocuploader/app/submission/conditions/HouseholdHasJob.java
  src/main/resources/flows-config.yaml
  src/test/java/org/ladocuploader/app/journeys/LaDigitalAssisterFlowJourneyTest.java
Labels: ready for review

#507 updated voting registration requested
  src/main/java/org/ladocuploader/app/submission/conditions/InterestedInVoterRegistration.java
  src/main/resources/flows-config.yaml
  src/test/java/org/ladocuploader/app/journeys/LaDigitalAssisterFlowJourneyTest.java
Labels: ready for review

#508 updated the footer copy minus FAQ
  src/main/resources/messages.properties
  src/main/resources/messages_es.properties
  src/main/resources/messages_vi.properties
  src/main/resources/templates/fragments/footer.html
Labels: InPM/DesignReview

#512 Limiting transmission batches to 25
  crontab
  src/main/java/org/ladocuploader/app/cli/SubmissionTransfer.java
  src/test/java/org/ladocuploader/app/cli/SubmissionTransferTest.java
Labels: ready for review

#516 fixed the about cookies link
  src/main/resources/messages.properties
Labels: ready for review

#505 updated income details preparer to show name of submitter
  src/main/java/org/ladocuploader/app/preparers/IncomeDetailsPreparer.java
  src/test/java/org/ladocuploader/app/preparers/IncomeDetailsPreparerTest.java
Labels: ready for review

#475 Session-scoped submissionID Bean
  messages_full.properties
  src/main/java/org/ladocuploader/app/config/DataRequiredHandlerConfiguration.java
  src/main/java/org/ladocuploader/app/config/SessionConfiguration.java
  src/main/java/org/ladocuploader/app/data/RecoverySubmissionIDs.java
  src/main/java/org/ladocuploader/app/interceptors/DataRequiredInterceptor.java
  src/test/java/org/ladocuploader/app/journeys/LaDigitalAssisterFlowJourneyTest.java
Labels: ready for review

#515 nested mailing address under if statement because mailing address key…
  src/main/resources/templates/laDigitalAssister/reviewContactInfo.html
Labels: ready for review

#529 added all missing fields
  src/main/resources/messages.properties
  src/main/resources/templates/laDigitalAssister/reviewContactInfo.html
Labels: WaitingOnDesignFeedback

#513 Add phone numbers to SNAP PDF
  src/main/resources/messages.properties
  src/main/resources/pdf-map.yaml
  src/main/resources/pdfs/la_application_for_assistance.pdf
Labels: InPM/DesignReview

#548 Update contact info
  src/main/java/org/ladocuploader/app/inputs/LaDigitalAssister.java
  src/main/java/org/ladocuploader/app/submission/actions/ValidateContactMethod.java
  src/main/java/org/ladocuploader/app/submission/conditions/PhoneNumberMissing.java
  src/main/resources/messages.properties
  src/main/resources/templates/laDigitalAssister/contactInfo.html
  src/test/java/org/ladocuploader/app/journeys/LaDigitalAssisterFlowJourneyTest.java
  src/test/java/org/ladocuploader/app/submission/actions/ValidateContactMethodTest.java
Labels: WaitingOnDesignFeedback

#547 Snap expedited application
  src/main/java/org/ladocuploader/app/preparers/ExpeditedSnapPreparer.java
  src/main/resources/pdf-map.yaml
  src/main/resources/pdfs/la_application_for_assistance.pdf
Labels: ready for review

#564 Fix aria attribute for doc type
  src/main/resources/templates/fragments/fileDetails.html
  src/main/resources/templates/fragments/inputs/selectCustom.html
  src/main/resources/templates/laDigitalAssister/docUploadType.html
Labels: ready for review

#576 Refactoring to track householdmember uuid in job subflow
  src/main/java/org/ladocuploader/app/preparers/IncomeDetailsPreparer.java
  src/main/java/org/ladocuploader/app/utils/IncomeCalculator.java
  src/main/java/org/ladocuploader/app/utils/SubmissionUtilities.java
  src/main/resources/messages.properties
  src/main/resources/templates/laDigitalAssister/householdEmployerName.html
  src/main/resources/templates/laDigitalAssister/householdIncomeWho.html
  src/main/resources/templates/laDigitalAssister/householdSelfEmployment.html
  src/main/resources/templates/laDigitalAssister/jobHourlyWage.html
  src/main/resources/templates/laDigitalAssister/jobHoursPerWeek.html
  src/main/resources/templates/laDigitalAssister/jobPaidByHour.html
  src/main/resources/templates/laDigitalAssister/jobPayPeriod.html
  src/test/java/org/ladocuploader/app/data/SubmissionTestBuilder.java
  src/test/java/org/ladocuploader/app/preparers/IncomeDetailsPreparerTest.java
Labels: ready for review

#565 SNAP transmission changes
  crontab
  src/main/java/org/ladocuploader/app/LaDocUploader.java
  src/main/java/org/ladocuploader/app/cli/FtpsClientImpl.java
  src/main/java/org/ladocuploader/app/cli/MockFtpsClientImpl.java
  src/main/java/org/ladocuploader/app/cli/MockPGPEncryptorImpl.java
  src/main/java/org/ladocuploader/app/cli/PGPEncryptorImpl.java
  src/main/java/org/ladocuploader/app/cli/SubmissionTransfer.java
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
  src/test/java/org/ladocuploader/app/cli/SubmissionTransferTest.java
Labels: ready for review

#583 Updating prod deploy script
  .github/workflows/deploy-prod.yaml
Labels: ready for review

#590 Clean up incomplete iterations in subflows after submission is signed
  src/main/java/org/ladocuploader/app/submission/actions/HandleApplicationSigned.java
Labels: ready for review
